### ISSUE TITLE
Please provide a guide on running the code

### ISSUE THREAD

**Issue by sunnypatel165** [apeeyush/Mail-Classifier#2]
Hi, I am sure many must have told you that this is a BRILLIANT project! 

Your ReadMe is wonderfully written as well. Just one thing would be that, it doesnt show how exactly to go about running the entire thing, ie see that actually the emails are sorted into folders. 

Basically i would like to try and contribute to this by:
1: Try other classifiers to see if they can imporve the accruacy?
2: To try and convert the JS part to python, ie make the entire project run as a python code(SVMs can be easily done in py as well).

So before i move ahead, please guide as to, how exactly to link these py-js files and see an output?

Waiting for your reply.

**Comment by luckysahani** [comment]
@apeeyush Please answer it !!!!

**Comment by sunnypatel165** [comment]
Never mind. I figured it out, i might write one soon and upload it in a couple of weeks.
Thanks anyways.
